export const UserActionTypes = {
  GOOGLE_SIGNIN_START: "GOOGLE_SIGNIN_START",
  GOOGLE_SIGNIN_SUCESS: "GOOGLE_SIGNIN_SUCESS",
  GOOGLE_SIGNIN_FAILURE: "GOOGLE_SIGNIN_FAILURE",
  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCESS: "SIGN_OUT_SUCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",
};
