import Head from "next/head";
import dynamic from "next/dynamic";
import styles from "../styles/Home.module.css";

const BgImage = dynamic(() => import("../components/background-image"), {
  ssr: false, //seeting server side rendering to false for BGimage
});

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>BRACKER</h1>
        <h2>Keep track of your records and Buisness efficient</h2>
        <BgImage />
      </main>
      <footer className={styles.footer}>wait for it</footer>
    </div>
  );
}
