import Head from "next/head";
import dynamic from "next/dynamic";
import styled from "styled-components";
import styles from "../styles/Home.module.css";

const BgImage = dynamic(() => import("../components/background-image"), {
  ssr: false, //setting server side rendering to false for BGimage
});

const Wrapper = styled.div`
  z-index: 1;
  width: 100%;
  height: 100%;
  position: fixed;
  justify-content: center;
  align-items: center;
  display: flex;
`;

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Wrapper>
          <h1>BRACKER</h1>
          <h2>Keep track of your records and Buisness efficient</h2>
          <footer className={styles.footer}>wait for it</footer>
        </Wrapper>
        <BgImage />
      </main>
    </div>
  );
}
